version: '3'

services:
  kafka:
    build: ./kafkamaster
    container_name: kafka
    networks:
      - kafkanetwork
    ports:
      - 2181:2181
      - 9092:9092
    command: bash -c "./roskafka.sh"

  consumer:
    build: ./kafkaproducer
    depends_on:
      - kafka
    networks:
      - kafkanetwork
    command: "python producer.py"
    restart: always

  producer:
    build: ./kafkaconsumer
    depends_on:
      - kafka
    networks:
      - kafkanetwork
    command: "python consumer.py"
    restart: always

networks:
  kafkanetwork: 
    driver: bridge
